version: "3"
services:
  grpc-server:
    container_name: grpc-server
    build:
      context: ./server
      dockerfile: Dockerfile.server
  grpc-client:
    container_name: grpc-client
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"